version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - n 14.18.3
  pre_build:
    commands:
      #install dependencies
      - echo Installing nvm...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
      - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
      - . "$NVM_DIR/nvm.sh" && nvm install 16.13.1
      - echo Installing node...
      - npm install -g pnpm
      - echo Installing node dependencies....
      - pnpm i
  build:
    commands:
      - echo Building...
      - pnpm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
